#! /bin/bash

set -e

INTERFACE=$(ip route | grep '^default' | grep -oP '(?<=dev )[^ \n]+')

if [ -z "${INTERFACE}" ]; then
    echo "interface"
    exit 1
fi

rm -f /tmp/whitelist_full_combine.txt

curl --silent --fail --interface "${INTERFACE}" --dns-interface "${INTERFACE}" --doh-url https://120.53.53.53/dns-query --output /tmp/whitelist_full_combine.txt https://cdn.jsdelivr.net/gh/hellodword/you-know-who@assets/adguard-home/whitelist_full_combine.txt

systemctl stop adguard-home || echo

mv /tmp/whitelist_full_combine.txt /usr/local/etc/adguard-home/whitelist_full_combine.txt

systemctl restart adguard-home

