name: adguard-home

on:
  schedule:
      - cron: "0 1 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'assets'
      - uses: actions/checkout@v4
        with:
          path: 'main-src'

      - name: config git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Run a multi-line script
        run: |
          mkdir -p adguard-home
          cd adguard-home
          rm whitelist_full_combine.txt
          rm ipset.txt
          bash ../main-src/adguard-home/generate.sh
          [ -f whitelist_full_combine.txt ]
          [ -f ipset.txt ]
          git add whitelist_full_combine.txt
          git add ipset.txt

      - name: rm main
        run: |
          rm -rf main-src

      - name: push
        run: |
          git commit -m ':sparkles:' || exit 0
          git push -u origin assets
