name: reading

on:
  schedule:
      - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'assets'
      - uses: actions/checkout@v4
        with:
          path: 'main-src'

      - name: config git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Run a multi-line script
        run: |
          mkdir -p shadowrocket
          cd shadowrocket
          rm -rf reading.list
          bash ../main-src/shadowrocket/reading.sh
          [ -f reading.list ]
          git add reading.list

      - name: rm main
        run: |
          rm -rf main-src

      - name: push
        run: |
          git commit -m ':sparkles:' || exit 0
          git push -u origin assets
